### ISSUE TITLE
Products shows blank page

### ISSUE THREAD

**Issue by filip-cermak** [themefisher/hargo#10]
I followed the install procedure, copied all files from the example folder to the root. All sites are showing correctly, only Products shows blank. Console shows:
![image](https://user-images.githubusercontent.com/47925995/82691117-b3c2c880-9c5d-11ea-83a3-94e0008e418a.png)

**Comment by somrat-gyver** [comment]
On localhost or netlify?

**Comment by developer-evan** [comment]
I am going to close this issue, if you feel something is not right, then reopen or create a new one. thanks
