### ISSUE TITLE
How to disable "Shopping cart" function ?

### ISSUE THREAD

**Issue by pythonsan** [themefisher/hargo#11]
Hello Author:

I like this template very much and is trying to use it in actual projects. But I have a problem: I don't need the shopping cart function yet. How can I disable this function?

My current needs are: click the button, the action is not the purchase, but the "inquiry" action, pop-up layer or jump page to enter the "contact me" function

I look forward to your support, thank you :-)

**Comment by pythonsan** [comment]
fix :-)

**Comment by Aarekaz** [comment]
@pythonsan How did you do it?

**Comment by pythonsan** [comment]
dear friend:

1. just disable plugin snipcart js
2.change the button name and event
