### ISSUE TITLE
Build Command is not showing up. What are the build commands for Nelify?

### ISSUE THREAD

**Issue by Aarekaz** [themefisher/hargo#12]
![unknown](https://user-images.githubusercontent.com/36888347/84274375-8461f600-ab4f-11ea-93a4-67719894252c.png)
 I tried a couple of times with different GitHub accounts but the build commands are not showing up. 
What should I put in this field? 
![unknown](https://user-images.githubusercontent.com/36888347/84275851-49f95880-ab51-11ea-9d21-aa1a45fcb944.png)

cc @rasiladhikari

**Comment by somrat-gyver** [comment]
Hey there, i have added netlify settings, please download the latest code
