### ISSUE TITLE
Change the color Scheme of the website and disqus not working

### ISSUE THREAD

**Issue by Aarekaz** [themefisher/hargo#13]
How can I change the color scheme of the whole website? There is no such thing in the config file. and I put my discus short name but seems like reviews are not working.

**Comment by Aarekaz** [comment]
and how to add products? The products are not adding from the file
![image](https://user-images.githubusercontent.com/36888347/84570616-54645e00-adae-11ea-955c-edf3d75eb04e.png)

**Comment by somrat-gyver** [comment]
hey there, you can't change the color scheme from forestry. you need to open this file in an editor. then open "assets/scss/variables.scss" and change the primary color.

**Comment by Aarekaz** [comment]
Okay Understood. And when I add a pre loader, the pre loader is not working. I think I got the default path wrong 
![image](https://user-images.githubusercontent.com/36888347/84584377-751acb00-ae23-11ea-81ed-b19b44845f8a.png)
The image is here.:- 
![image](https://user-images.githubusercontent.com/36888347/84584393-9f6c8880-ae23-11ea-8d44-789a49bb0d7b.png)

Any Idea whats happening?

**Comment by somrat-gyver** [comment]
Hey there, thanks for your concern, I fixed this issue. please download the latest code. thanks

**Comment by Aarekaz** [comment]
Which which issues are fixed? Thank you

**Comment by somrat-gyver** [comment]
Prelaoder Issue

**Comment by Aarekaz** [comment]
Which files should i re download? 
And can you add forestry settings? I manually added some

**Comment by somrat-gyver** [comment]
You need to replace the "layouts/partial/preloader.html" file.

We will add forestry to all our theme step by step. if you need urgently then contact us at themefisher@gmail.com

**Comment by Aarekaz** [comment]
Okay! Will contact you later! Thank you for the help!

**Comment by Aarekaz** [comment]
@somrat-gyver So even if i change the color, the website is not working
![image](https://user-images.githubusercontent.com/36888347/85254010-0c64cb80-b47f-11ea-9a45-b5082856f31a.png)
![image](https://user-images.githubusercontent.com/36888347/85254020-138bd980-b47f-11ea-870b-d3c03eb89f54.png)

**Comment by developer-evan** [comment]
try to clear your browser cache

**Comment by grego-e** [comment]
You need to use hugo's extended version, normal hugo does not support toCSS.

**Comment by developer-evan** [comment]
Is your problem has solved? I am going to close this issue, if you have more concerns, then re-open this issue or create a new one.

also if you like our template, a star would be amazing. thanks
