### ISSUE TITLE
How do we add search to this?

### ISSUE THREAD

**Issue by shaan1991** [themefisher/hargo#16]
Can you help me add search to this template?

**Comment by developer-evan** [comment]
hey there, adding search is a complex process. you can't actually do it if you don't have knowledge of Hugo and javascript. you can contact us for paid support at themefisher@gmail.com to add or customization of this template. thanks

**Comment by JAVYMOON** [comment]
Hi! How can I use a whatsapp plugin for this site? 
It's easy to implement?

**Comment by developer-evan** [comment]
hey there, i have never implimented that. It will be great if you searching it on google or disqus on hugo forum. thanks
