### ISSUE TITLE
Help me configure forestry please.

### ISSUE THREAD

**Issue by shaan1991** [themefisher/hargo#17]

**Comment by developer-evan** [comment]
hey there, please follow forestry documentation to do that. I don't know how to help you here. you need to create a forestry account, then import your site there, then just follow the steps that forestry suggests you.

also if you like our template, give us a star. we will appreciate it. thanks

**Comment by shaan1991** [comment]
Thanks a lot... I've starred 😊

**Comment by developer-evan** [comment]
I am going to close this issue, if you need any help you can reopen this issue or create a new one.

also if you like our theme, a star would be amazing. thanks for being with themefisher.
