### ISSUE TITLE
no theme is loaded

### ISSUE THREAD

**Issue by rcastellotti** [themefisher/hargo#3]
i just installed the theme with git submoudle..., to test locally i have set `baseUrl="/"` and `theme="hargo"`, but when browsing `localhost:1313` the theme is not loaded, here you can see a screenshot of what is loaded, what am I doing wrong?
![Screenshot from 2020-01-08 21-47-14](https://user-images.githubusercontent.com/43064224/72014616-82260380-3260-11ea-90ed-a0be763e65b5.png)

**Comment by themefisherDev** [comment]
Did you tried just clone or download this template?

**Comment by rcastellotti** [comment]
i cloned it, and running `hugo server -D` is actually the same

**Comment by themefisherDev** [comment]
@rcastellotti , 

I don't know why you are facing this issue, I just clone and run this theme locally, and it works absolutely fine. 
Let's try from the beginning by following this instructions. first you clone this repository and then open it with terminal, then run this two commands.
```
cd exampleSite/
hugo server --themesDir ../..
```

**Comment by themefisherDev** [comment]
@rcastellotti .

did your problem solved?

**Comment by dbryar** [comment]
the example site is needed to actually demo the theme. 

From your project directory;

``` 
cd themes/hargo/exampleSite; hugo -t hargo --themesDir ../.. server
```
and it will work. Now you need to pull the example layout and partials in to your own content...

**Comment by dbryar** [comment]
@themefisherDev The 'installation' documentation is a bit lacking, and need to go further in to how a dev would start to apply their content to the them, e.g. creating the required folders, indexes, etc. I just came here to see if there was any more than the generic stuff in the main readme.md
