### ISSUE TITLE
Snipcart Validation Fails

### ISSUE THREAD

**Issue by ccapasso01** [themefisher/hargo#4]
I have this theme loading and working fine.  Upon uploading to Netlify, when testing Snipcart (after updating to my test API key from Snipcart), when you go to checkout, it fails stating the following:

`POST https://app.snipcart.com/api/cart/d31ad6da-30be-4035-8313-f5341dc752a3/pay 400 (Bad Request)
snipcart.js:8 Snipcart:  We have not been able to find item at 'https://patsrelicroom.netlify.com/products/taba-shampoo.1/'. 
                Please validate the URL and we suggest you take a look at the Security section 
                of our documentation (http://docs.snipcart.com/getting-started/security) to 
                understand how our validation works.
`

From what I can tell, it looks like the items aren't passing a valid URL for some reason.  I'm assuming there is something missing configuration wise, but would very much appreciate some assistance :).

If you'd like to test yourself, the site is live here: https://patsrelicroom.netlify.com

Full disclosure, I have a lot more work to do for uploading actual products, changing the data still, etc.  But I would think the theme that is supposed to work with Snipcart should work with minimal changes.

**Comment by ccapasso01** [comment]
Solved....turns out there is a step you have to do inside of the snipcart dashboard.  you must setup your default domain.  once this is done, everything works as it should with one exception.  the default prices in this template need updated to just a numeric value. having an amount of 30.00$ for example, throws an error by snipcart stating that the price is invalid.

**Comment by xx7Ahmed7xx** [comment]
How can we solve this issue locally ?
