### ISSUE TITLE
TOCSS error

### ISSUE THREAD

**Issue by Tanoh-Hermann** [themefisher/hargo#6]
Error building site: TOCSS: failed to transform "scss/style.scss" (text/x-scss): resource "scss/scss/style.scss_b95b077eb505d5c0aff8055eaced30ad" not found in file cache

**Comment by savage-teddy** [comment]
@Tanoh-Hermann, did you find a solution for this... having the same problem.

**Comment by Somrat37** [comment]
Which version of hugo you are using?

**Comment by savage-teddy** [comment]
@Somrat37 

Hugo version v0.70.0-DEV

I was able to start the server by running it from within the exampleSite ( Reference issue #3 [.](https://github.com/themefisher/hargo/issues/3) ) Running it from the top level directory results in the given error.

**Comment by Somrat37** [comment]
please download and install the hugo extended version

**Comment by Somrat37** [comment]
Did it solve your issue? I am going to close this issue, if you have any other problem then create a new issue. Thanks

**Comment by sfid98** [comment]
@Somrat37 
I had the same error and by installing the "hugo extended version" i have solve the issue.
Thank you very much.

**Comment by Slevin2017** [comment]
> @Somrat37
> I had the same error and by installing the "hugo extended version" i have solve the issue.
> Thank you very much.

May I ask you to tell me about your solution to this problem.

**Comment by savage-teddy** [comment]
@Somrat37 and @sfid98 , installing the extended version did fix the problem.

@Slevin2017 they are referring to [here](https://gohugo.io/getting-started/installing/#fetch-from-github). Note the line to get the extended version => `go install --tags extended`

**Comment by Slevin2017** [comment]
Thank you very much! It seems to have the problem with gcc.)

**Comment by savage-teddy** [comment]
@Slevin2017 , I assume you using windows machine with something like cygwin? If so (and even if you are using something else and gcc is failing) there is an fairly easy way to do this using a Docker container and mount your project directory to it.

You can use this docker image [hugo-extended](https://hub.docker.com/r/trenton/hugo-extended) and write a **docker-compose.yaml** file similar to this...

    version: "3.7"
    services:
        web:
          image: trenton/hugo-extended:latest
          ports: 
            - 1313:1313
          restart: unless-stopped
          volumes:
            - ./your_project_directory:/site
          command: hugo server -D --bind 0.0.0.0

Then just start it with `docker-compose up` and make changes and see them update just like you would if you ran the hugo command on your local machine.

**Comment by sakashushu** [comment]
すげぇ！「extended version」ってやつか。それに置き換えたらホントにできた！ありがとうございました！
