### ISSUE TITLE
how do u add children in navbar?

### ISSUE THREAD

**Issue by codeitlikemiley** [themefisher/hargo#8]
how can i define if menu.main has many child?
I see the code is built with parent menu in mind, 
i would like to have a drop down and define all the children and links below
how would i define that in the config.toml

**Comment by Somrat37** [comment]
You can do it like this

`[[menu.main]]
weight = 3
name = "dropdown"
hasChildren = true

  [[menu.main]]
  parent = "dropdown"
  name = "Installation"
  url = "#"
  weight = 1

  [[menu.main]]
  parent = "dropdown"
  name = "Billing"
  url = "#"
  weight = 2`
