### ISSUE TITLE
Snipcart 3.x

### ISSUE THREAD

**Issue by filip-cermak** [themefisher/hargo#9]
Would it be possible to update this theme for Snipcart 3.x? Or at least give a description, how to do it?

**Comment by somrat-gyver** [comment]
yes, you can follow snipcart documentation for doing this.

**Comment by developer-evan** [comment]
I am going to close this issue, if you feel something is not right, then reopen or create a new one. thanks

**Comment by bartmika** [comment]
Added support via https://github.com/themefisher/hargo/pull/19
